### ISSUE TITLE
BFDA.sim "t.paired" error

### ISSUE THREAD

**Issue by lnalborczyk** [nicebread/BFDA#1]
Hello, following your advices, I recently started using the BFDA package. However, I experience some troubles when it comes to within-subject designs. For instance, the following command:

`sim <- BFDA.sim(expected.ES = 0.666, type = "t.paired")`

gives me this error:

`[1] "Simulation started at ..."`

`Error in { : task 1 failed - "unused argument (SD = 1)"`

Is it a normal behaviour? Do I need to pass extra arguments to the function for within designs? Thanks for your help and thanks for the great work.

Best regards,
Ladislas

**Comment by nicebread** [comment]
It was a bug in the t.paired functions. Should work now!
