### ISSUE TITLE
Installation issues on R version 3.6.2

### ISSUE THREAD

**Issue by hannehuygelier** [nicebread/BFDA#13]
Dear developers,

I have been trying to install the BFDA package, but have run into some issues. First, the installation always failed on installing dependencies. So I manually installed all dependencies.

Now, all the dependencies are installed/upgraded, but the installation still fails. I cannot make sense of the error message.

This is the code I run:
```
library(devtools)
install_github("nicebread/BFDA", subdir="package")

```

This is the message that is printed when installing:

> Downloading GitHub repo nicebread/BFDA@master
> √  checking for file 'C:\Users\u0097836\AppData\Local\Temp\RtmpyunqBr\remotes36f415daf4c\nicebread-BFDA-9a03b85\package/DESCRIPTION' (445ms)
> -  preparing 'BFDA': (1.5s)
> √  checking DESCRIPTION meta-information ... 
> -  cleaning src
> -  checking for LF line-endings in source and make files and shell scripts
> -  checking for empty or unneeded directories
>      NB: this package now depends on R (>= 3.5.0)
>      WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/abtest_walkthrough_77d8b299313465089768b2e8f4ac2b1a.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/abtest_walkthrough_77d8b299313465089768b2e8f4ac2b1a.rdx'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/corr_walkthrough_272e7da792a2e7f28cd804a1e16f97e1.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/corr_walkthrough_272e7da792a2e7f28cd804a1e16f97e1.rdx'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/paired.t_669ee583ef1b3452e61e21e2c5d492b8.RData'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'BFDA/vignettes/BFDA_manual_cache/latex/paired.t_669ee583ef1b3452e61e21e2c5d492b8.rdx'
> -  building 'BFDA_0.5.0.tar.gz'
>    
> Installing package into ‘C:/Users/u0097836/Documents/R/win-library/3.6’
> (as ‘lib’ is unspecified)
> * installing *source* package 'BFDA' ...
> ** using staged installation
> ** libs
> 
> *** arch - i386
> C:/RBuildTools/3.4/mingw_32/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/u0097836/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
> C:/RBuildTools/3.4/mingw_32/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/u0097836/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c minl_functions.cpp -o minl_functions.o
> C:/RBuildTools/3.4/mingw_32/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o BFDA.dll tmp.def RcppExports.o minl_functions.o -LC:/PROGRA~1/R/R-36~1.2/bin/i386 -lR
> installing to C:/Users/u0097836/Documents/R/win-library/3.6/00LOCK-BFDA/00new/BFDA/libs/i386
> 
> *** arch - x64
> C:/RBuildTools/3.4/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/u0097836/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
> C:/RBuildTools/3.4/mingw_64/bin/g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG  -I"C:/Users/u0097836/Documents/R/win-library/3.6/Rcpp/include"        -O2 -Wall  -mtune=generic -c minl_functions.cpp -o minl_functions.o
> C:/RBuildTools/3.4/mingw_64/bin/g++ -std=gnu++11 -shared -s -static-libgcc -o BFDA.dll tmp.def RcppExports.o minl_functions.o -LC:/PROGRA~1/R/R-36~1.2/bin/x64 -lR
> installing to C:/Users/u0097836/Documents/R/win-library/3.6/00LOCK-BFDA/00new/BFDA/libs/x64
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> Error: (converted from warning) package 'doParallel' was built under R version 3.6.3
> Execution halted
> ERROR: lazy loading failed for package 'BFDA'
> * removing 'C:/Users/u0097836/Documents/R/win-library/3.6/BFDA'
> Error: Failed to install 'BFDA' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/u0097836/AppData/Local/Temp/RtmpyunqBr/file36f426173dc0/BFDA_0.5.0.tar.gz’ had non-zero exit status

What is the exact issue and how can I solve it?

Kind regards,
Hanne

**Comment by nicebread** [comment]
This warning suggests that you have to upgrade to R 3.6.3:
> Error: (converted from warning) package 'doParallel' was built under R version 3.6.3
