### ISSUE TITLE
SSD function error

### ISSUE THREAD

**Issue by ChristineBlume** [nicebread/BFDA#16]
Following the example on https://rawgit.com/nicebread/BFDA/master/package/doc/BFDA_manual.html I receive the following error when using the SSD function:
Error in if (var.ns > 0) { : Missing value, where TRUE/FALSE is needed.

**Comment by astefan1** [comment]
Hi Christine, sorry for the super late reply! This error occurs when you're using a fixed-N BFDA object with the SSD function. What you need is a sequential BFDA object of the following form BFDA.sim(..., design = "sequential", n.max = 500, boundary = Inf, ...) (n.max is set to an arbitrary large number where you can be decently sure that you will achieve the power you're planning for). This obviously needs a fix (i.e., an understandable error message), but in principle, the function should work.

**Comment by astefan1** [comment]
I fixed this (added an understandable error message); see [this commit](https://github.com/nicebread/BFDA/commit/fc80e5ec4d2c2ee315c95e3d81870ccf362631c0)
