### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by dtlammer** [nicebread/BFDA#19]
Good Morning, 
I am trying to upload the package per the instructions and am having issues. I would like to use the package to help design a clinical trial prior to applying for a grant. Any and all help is appreciated!

Below is my .r code:
> library(devtools)
> install_github("nicebread/BFDA", subdir = "package")
Downloading GitHub repo nicebread/BFDA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/nicebread/BFDA/tarball/HEAD' failed

Thank you!
-Danny

**Comment by nicebread** [comment]
Hi Danny, 

the code works for me - the error message could imply that you had no internet connection? Does it work now?

**Comment by dtlammer** [comment]
Hi Felix,
Thank you for the message. Yes, I was able to get it to work. Thanks again!
-Danny

**Comment by nicebread** [comment]
OK, great!
