### ISSUE TITLE
How do I run the test once the data are collected

### ISSUE THREAD

**Issue by kalenkovich** [nicebread/BFDA#9]
I ran BFDA simulations prior to collecting the data. Now that I've actually collected the data, I would like to apply the same test that was used during the simulations.

I ran the simulations with

```r
BFDA.sim(
  expected.ES = ?,
  type = "t.paired",
  prior = list("t",
               list(
               prior.location = 0.35,
               prior.scale = 0.102,
               prior.df = 3
               )),
  alternative = 'greater',
  n.min = 10,
  n.max = 50,
  stepsize = 5,
  boundary = c(1/6, 6),
  verbose = TRUE,
  cores = 2,
  B = 5000
  )
```

What is the correct way to run the test in my case? Here is my current guess:

```r
prior <- list("t",
              list(
                prior.location = 0.35,
                prior.scale = 0.102,
                prior.df = 3
              ))
alternative <- 'greater'

freq.test <- BFDA:::freq.test.t.paired(
  SAMP = x, alternative = alternative)
logBF <- BFDA:::BF.test.t.paired(
  SAMP = x, alternative = alternative, 
  freq.test = freq.test, 
  prior = prior)
```
where `x` contains pair differences in my data.

**Comment by astefan1** [comment]
Hi @kalenkovich,

sorry for the late reply! What you computed looks good to me.

Alternatively, you can also use the internal function bf10_t where you directly enter the t statistic from your sample. This will give you the Bayes factor (not the log Bayes factor)

``` r
all.BF <- BFDA:::bf10_t(t = t.value, n1 = final.sample.size, independentSamples = FALSE,
prior.location = 0.35, prior.scale. = 0.102, prior.df = 3)
BF.directional <- all.BF[["BFplus0"]]
```

The informed t-test was developed by [Gronau et al., 2019](www.doi.org/10.1080/00031305.2018.1562983). You can read the specifics about the Bayesian t-test functions in their paper.

Cheers,
Angelika

**Comment by astefan1** [comment]
Hi @kalenkovich,

sorry for the late reply! What you computed looks good to me.

Alternatively, you can also use the internal function bf10_t where you directly enter the t statistic from your sample. This will give you the Bayes factor (not the log Bayes factor)

``` r
all.BF <- BFDA:::bf10_t(t = t.value, n1 = final.sample.size, independentSamples = FALSE,
prior.location = 0.35, prior.scale. = 0.102, prior.df = 3)
BF.directional <- all.BF[["BFplus0"]]
```

The informed t-test functions were written by [Gronau et al. (2019)](doi.org/10.1080/00031305.2018.1562983). You can read about the specifics of the Bayesian t-test functions in their paper.

Let me know if you have any further questions.

Cheers,
Angelika

**Comment by kalenkovich** [comment]
Thank you @astefan1! I'll take a look at the paper.
